dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
  slack:
   rooms:
     secure: "liTmko2kW/NC1yTRJnpjzhj88w5ySiTRQdik8tSIlV2Cb4qjOEbg8k7znwGRftFygQZbUkDKGWShfhiKpaO5TAH4xjJrS/Hdt0ZD04QY23ld79cVMEG9p3bghUsW3pJIqKEUViUKloSDO/wQr2xvrWKuNqrWsgpP58wrxVI/b14Ll41nuCgm2FoDFkibM7HJOoagpk1bScAaBOixr7z1XVDheUalm3j/Zmv+j7RL8s7FniynjuCBzCQaAH/mYhVIFj8TmAYAn2HgSN1Rlru4IcY6usvvhb6rfHWwdlri2Bx+CTdTYhAOlGSzEbB/zLwZfhb8WxnQrjIccRaYyLqyt1S9svxsQyyzj8NUhW5NHtPYJTv5PAGk1xTSy+OtW3+v2ePaIIXk1RblPDVZK1SOzNMdvrYbKQ1BPSpiaq/Tfpp9kkVfHK0G+90JEiYx2PXLI28Uo80xkatqHeXLhx+UYn7jAGwm2hGMenWTI6T4CP5HpAmSVlBJKnyt1Tbf4BQyk/bTAIQQFCGnMSVizZ/U6Ppj3HxZGRUsd64FhJsICUOup9+WfNHFA1HkXwZqp4c+8HxTlRnnYFZ8nHPhmDLExhagDKPygLMxkK4zfsb9mxE9zMA66gV5zRcVDkrvEIw2q9FydyAQlEgnO17KfFR2VM2RPUofc1f8Yy+CfPr0eew="
