dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
  slack:
   rooms:
     secure: CVYb0qfPHt5o+/apdhc9MF+kQqquShyXpGeYhokXI48rwaKjBFBYy2FF6rzxvi+FrZwfPaOKyzLmftk79hIcOwlMu/zvfxrrEgE5StEi5sdbCNO70vYjn3eP+6bFrA5hxQC7ugtqtMfn/Cv5hWtaMIamaETsTFQVjH2ty7kY1sZDY2JYTz0YaC0NEw+o/fE+rksp2kkXQO3P/7S8pKD1RSoqsaoEoJhA7Zmz1DDvsKWjXhrcPP4BRTQaqH5cKuPs77tHpnfOa8uJZJm/WMAUvPbJ93lNee85BxeKWlovIdWIjoNJ98h6DEd1U99W7MPa5Qqq/LGD3Z/yY8l6USkLunJqTlLlkcRooO33gIv4Aof4dx/fDf5uEcjhc2oEkXoOTTKDdC8odO5H49ZL/x/V5jVm7A2S7awRFufMlLEsJjZ/KC+bXIA234fx638NALX0jfcXwIhz8w4su1Cdv98isn4AXhe8z3Vq7PAd/NS3bBm0t8Ic2xK56MtMwlfBf5EctFeW5c5Pj5mcEPvuYRlKs+SLynwyCa0snZc+sXcgD3U+JAuukm2HQd0Zh6YGwV9wrkQXzQCh3dMbO2nX83fe14ZL6PPY1/YQHjirhpSeZ3pI71YGk71SdUdoupGlIycdKkXfhHkkvSPsUal/FUt7SThPhk9nbk4rrPT4dJ8cNlg=
