plugin: gcp_compute
projects:
  - infra-271019
zones:
  - "europe-west4-a"
groups:
  db: "'db' in name"
  app: "'app' in name"
filters: []
auth_kind: serviceaccount
service_account_file: "./environments/stage/gcpkey.json"
